-- +migrate Up
-- +migrate StatementBegin

CREATE TABLE users (
                       id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       username varchar NOT NULL,
                       password varchar NOT NULL,
                       created_at timestamp DEFAULT NOW(),
                       created_by varchar,
                       modified_at timestamp DEFAULT NOW()
);

INSERT INTO users(username, password, created_by) VALUES('admin', 'admin', 'admin')

-- +migrate StatementEnd