-- +migrate Up
-- +migrate StatementBegin

CREATE TABLE categories (
                            id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                            name varchar NOT NULL,
                            created_at timestamp DEFAULT NOW(),
                            created_by varchar,
                            modified_at timestamp DEFAULT NOW(),
                            modified_by varchar
);

-- +migrate StatementEnd