-- +migrate Up
-- +migrate StatementBegin

CREATE TABLE books (
                       id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       title varchar NOT NULL,
                       description varchar NOT NULL,
                       image_url varchar NOT NULL,
                       release_year integer NOT NULL,
                       price integer NOT NULL,
                       total_page integer NOT NULL,
                       thickness varchar NOT NULL,
                       category_id integer REFERENCES categories (id) ON UPDATE CASCADE ON DELETE CASCADE,
                       created_at timestamp DEFAULT NOW(),
                       created_by varchar,
                       modified_at timestamp DEFAULT NOW(),
                       modified_by varchar
);

-- +migrate StatementEnd